# Generated by Django 5.2 on 2025-05-03 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='custom_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 3, 6, 22, 17, 216354, tzinfo=datetime.timezone.utc)),
        ),
    ]
